// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEmchrXBUjIcepXy24JUqgaEljs2cKats',
    appId: '1:819546911668:web:b16bec5196a149a1f8f8e1',
    messagingSenderId: '819546911668',
    projectId: 'isft182-90d16',
    authDomain: 'isft182-90d16.firebaseapp.com',
    storageBucket: 'isft182-90d16.firebasestorage.app',
    measurementId: 'G-PSY7E45W5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhixp-1cL716XMEE4W6KUuADtcRnb8iH0',
    appId: '1:819546911668:android:028e15624dfcdc6df8f8e1',
    messagingSenderId: '819546911668',
    projectId: 'isft182-90d16',
    storageBucket: 'isft182-90d16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjBXVN8xP-XhJaJV0F9jvR9f_dwPkHKBE',
    appId: '1:819546911668:ios:bca93d3e60b5334df8f8e1',
    messagingSenderId: '819546911668',
    projectId: 'isft182-90d16',
    storageBucket: 'isft182-90d16.firebasestorage.app',
    iosBundleId: 'com.example.miAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjBXVN8xP-XhJaJV0F9jvR9f_dwPkHKBE',
    appId: '1:819546911668:ios:bca93d3e60b5334df8f8e1',
    messagingSenderId: '819546911668',
    projectId: 'isft182-90d16',
    storageBucket: 'isft182-90d16.firebasestorage.app',
    iosBundleId: 'com.example.miAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEmchrXBUjIcepXy24JUqgaEljs2cKats',
    appId: '1:819546911668:web:a70410645c0b1966f8f8e1',
    messagingSenderId: '819546911668',
    projectId: 'isft182-90d16',
    authDomain: 'isft182-90d16.firebaseapp.com',
    storageBucket: 'isft182-90d16.firebasestorage.app',
    measurementId: 'G-ZJYDYBDZFH',
  );
}
